# ============================================================================
# Logging Configuration - Kedro 1.1.1 Compatible
# ============================================================================
version: 1

formatters:
  simple:
    format: "[%(asctime)s] %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/kedro.log
    mode: w

root:
  level: INFO
  handlers:
    - console
    - file

loggers:
  kedro:
    level: INFO
    handlers:
      - console
      - file
  
  ml_engine:
    level: DEBUG
    handlers:
      - console
      - file
